/*
                                +++ TPC-H 10GB Setup

STEPS:
  >>> RUN ALL THE QUERIES (FAR LEFT GREEN PLAY BUTTON) TO:
        > CREATE SCHEMA
        > CREATE TABLES
        > IMPORT DATA DIRECTLY FROM PARQUET FILES IN AMAZON S3 ON AWS: https://docs.exasol.com/db/latest/loading_data/load_data_parquet.htm
        > MAKE SURE YOUR COMMUNITY EDITION IS CONNECTED TO THE INTERNET AND YOUR FIREWALL DOES NOT BLOCK TRAFFIC TO AMAZON S3

-- Estimated times on 4vcpu, 8gb memory and a 100Mbit Internet Connection ~10mins
-- Import performance heavily depends on your internet connection speed and also increases with more nodes, vCPU and RAM

-- Next, Go to Bookmarks > 1 - Getting Started > 06 - TPC-H 10GB Queries.sql

*/

-- BEGIN

-- ### SCHEMAS ###
DROP SCHEMA IF EXISTS TPCH_10GB CASCADE;
CREATE SCHEMA TPCH_10GB;

-- ### TABLES ###
CREATE OR REPLACE TABLE "TPCH_10GB"."CUSTOMER" ("C_CUSTKEY" DECIMAL(18,0) NOT NULL ,"C_NAME" VARCHAR(25) ASCII ,"C_ADDRESS" VARCHAR(40) ASCII ,"C_NATIONKEY" DECIMAL(18,0) ,"C_PHONE" CHAR(15) ASCII ,"C_ACCTBAL" DECIMAL(18,2) ,"C_MKTSEGMENT" CHAR(10) ASCII ,"C_COMMENT" VARCHAR(117) ASCII , CONSTRAINT "PK_CUSTOMER" PRIMARY KEY (C_CUSTKEY) DISABLE);
CREATE OR REPLACE TABLE "TPCH_10GB"."LINEITEM" ("L_ORDERKEY" DECIMAL(18,0) NOT NULL ,"L_PARTKEY" DECIMAL(18,0) ,"L_SUPPKEY" DECIMAL(18,0) ,"L_LINENUMBER" DECIMAL(18,0) NOT NULL ,"L_QUANTITY" DECIMAL(18,2) ,"L_EXTENDEDPRICE" DECIMAL(18,2) ,"L_DISCOUNT" DECIMAL(18,2) ,"L_TAX" DECIMAL(18,2) ,"L_RETURNFLAG" CHAR(1) ASCII ,"L_LINESTATUS" CHAR(1) ASCII ,"L_SHIPDATE" DATE ,"L_COMMITDATE" DATE ,"L_RECEIPTDATE" DATE ,"L_SHIPINSTRUCT" CHAR(25) ASCII ,"L_SHIPMODE" CHAR(10) ASCII ,"L_COMMENT" VARCHAR(44) ASCII , CONSTRAINT "PK_LINEITEM" PRIMARY KEY (L_LINENUMBER,L_ORDERKEY) DISABLE);
CREATE OR REPLACE TABLE "TPCH_10GB"."NATION" ("N_NATIONKEY" DECIMAL(18,0) NOT NULL ,"N_NAME" CHAR(25) ASCII ,"N_REGIONKEY" DECIMAL(18,0) ,"N_COMMENT" VARCHAR(152) ASCII , CONSTRAINT "PK_NATION" PRIMARY KEY (N_NATIONKEY) DISABLE);
CREATE OR REPLACE TABLE "TPCH_10GB"."ORDERS" ("O_ORDERKEY" DECIMAL(18,0) NOT NULL ,"O_CUSTKEY" DECIMAL(18,0) ,"O_ORDERSTATUS" CHAR(1) ASCII ,"O_TOTALPRICE" DECIMAL(18,2) ,"O_ORDERDATE" DATE ,"O_ORDERPRIORITY" CHAR(15) ASCII ,"O_CLERK" CHAR(15) ASCII ,"O_SHIPPRIORITY" DECIMAL(10,0) ,"O_COMMENT" VARCHAR(79) ASCII , CONSTRAINT "PK_ORDERS" PRIMARY KEY (O_ORDERKEY) DISABLE);
CREATE OR REPLACE TABLE "TPCH_10GB"."PART" ("P_PARTKEY" DECIMAL(18,0) NOT NULL ,"P_NAME" VARCHAR(55) ASCII ,"P_MFGR" CHAR(25) ASCII ,"P_BRAND" CHAR(10) ASCII ,"P_TYPE" VARCHAR(25) ASCII ,"P_SIZE" DECIMAL(10,0) ,"P_CONTAINER" CHAR(10) ASCII ,"P_RETAILPRICE" DECIMAL(18,2) ,"P_COMMENT" VARCHAR(23) ASCII , CONSTRAINT "PK_PART" PRIMARY KEY (P_PARTKEY) DISABLE);
CREATE OR REPLACE TABLE "TPCH_10GB"."PARTSUPP" ("PS_PARTKEY" DECIMAL(18,0) NOT NULL ,"PS_SUPPKEY" DECIMAL(18,0) NOT NULL ,"PS_AVAILQTY" DECIMAL(10,0) ,"PS_SUPPLYCOST" DECIMAL(18,2) ,"PS_COMMENT" VARCHAR(199) ASCII , CONSTRAINT "PK_PARTSUPP" PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY) DISABLE);
CREATE OR REPLACE TABLE "TPCH_10GB"."REGION" ("R_REGIONKEY" DECIMAL(18,0) NOT NULL ,"R_NAME" CHAR(25) ASCII ,"R_COMMENT" VARCHAR(152) ASCII , CONSTRAINT "PK_REGION" PRIMARY KEY (R_REGIONKEY) DISABLE);
CREATE OR REPLACE TABLE "TPCH_10GB"."SUPPLIER" ("S_SUPPKEY" DECIMAL(18,0) NOT NULL ,"S_NAME" CHAR(25) ASCII ,"S_ADDRESS" VARCHAR(40) ASCII ,"S_NATIONKEY" DECIMAL(18,0) ,"S_PHONE" CHAR(15) ASCII ,"S_ACCTBAL" DECIMAL(18,2) ,"S_COMMENT" VARCHAR(101) ASCII , CONSTRAINT "PK_SUPPLIER" PRIMARY KEY (S_SUPPKEY) DISABLE);

-- ### FOREIGN KEYS ###
ALTER TABLE "TPCH_10GB"."SUPPLIER" ADD CONSTRAINT "FK_NATION" FOREIGN KEY ("S_NATIONKEY") REFERENCES "TPCH_10GB"."NATION" DISABLE;
ALTER TABLE "TPCH_10GB"."PARTSUPP" ADD CONSTRAINT "FK_PART" FOREIGN KEY ("PS_PARTKEY") REFERENCES "TPCH_10GB"."PART" DISABLE;
ALTER TABLE "TPCH_10GB"."LINEITEM" ADD CONSTRAINT "FK_ORDER" FOREIGN KEY ("L_ORDERKEY") REFERENCES "TPCH_10GB"."ORDERS" DISABLE;
ALTER TABLE "TPCH_10GB"."CUSTOMER" ADD CONSTRAINT "FK_NATION" FOREIGN KEY ("C_NATIONKEY") REFERENCES "TPCH_10GB"."NATION" DISABLE;
ALTER TABLE "TPCH_10GB"."PARTSUPP" ADD CONSTRAINT "FK_SUPP" FOREIGN KEY ("PS_SUPPKEY") REFERENCES "TPCH_10GB"."SUPPLIER" DISABLE;
ALTER TABLE "TPCH_10GB"."LINEITEM" ADD CONSTRAINT "FK_PARTSUPP" FOREIGN KEY ("L_PARTKEY","L_SUPPKEY") REFERENCES "TPCH_10GB"."PARTSUPP" DISABLE;
ALTER TABLE "TPCH_10GB"."ORDERS" ADD CONSTRAINT "FK_CUSTOMER" FOREIGN KEY ("O_CUSTKEY") REFERENCES "TPCH_10GB"."CUSTOMER" DISABLE;
ALTER TABLE "TPCH_10GB"."NATION" ADD CONSTRAINT "FK_REGION" FOREIGN KEY ("N_REGIONKEY") REFERENCES "TPCH_10GB"."REGION" DISABLE;

-- ### DISTRIBUTION KEYS ###
ALTER TABLE "TPCH_10GB"."ORDERS" DISTRIBUTE BY "O_CUSTKEY";
ALTER TABLE "TPCH_10GB"."LINEITEM" DISTRIBUTE BY "L_ORDERKEY";
ALTER TABLE "TPCH_10GB"."CUSTOMER" DISTRIBUTE BY "C_CUSTKEY";
ALTER TABLE "TPCH_10GB"."PART" DISTRIBUTE BY "P_PARTKEY";
ALTER TABLE "TPCH_10GB"."PARTSUPP" DISTRIBUTE BY "PS_PARTKEY";
ALTER TABLE "TPCH_10GB"."SUPPLIER" DISTRIBUTE BY "S_SUPPKEY";

-- ### IMPORT DATA ###

IMPORT INTO TPCH_10GB.CUSTOMER
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/customer.parquet'
;

IMPORT INTO TPCH_10GB.PARTSUPP
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/partsupp.parquet'
;

IMPORT INTO TPCH_10GB.ORDERS
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/orders.parquet'
;

IMPORT INTO TPCH_10GB.LINEITEM
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/lineitem.parquet'
;

IMPORT INTO TPCH_10GB.PART
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/part.parquet'
;

IMPORT INTO TPCH_10GB.SUPPLIER
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/supplier.parquet'
;

IMPORT INTO TPCH_10GB.NATION
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/nation.parquet'
;

IMPORT INTO TPCH_10GB.REGION
FROM PARQUET AT EXASOL_AWS_S3_PARQUET_TPCH_DEMO
FILE 'tpch/10GB/region.parquet'
;

-- DONE

-- Next, Go to Bookmarks > 1 - Getting Started > 06 - TPC-H 10GB Queries.sql
